#!/bin/bash
#
# test the ls command with a lot of commas at first
command2="This program was developed by Paula Fuentes and Oscar Riaño,
 as a proposed study project in Holberton Colombia.

November 2019
You are free to download the files and run the program, but please don't cheat.
Then use help paula and help oscar"
command="help"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == command2 ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file